ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(30);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS force_password_change BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();

UPDATE users
SET role = CASE
    WHEN email = 'admin@sante.com' THEN 'SUPER_ADMIN'
    WHEN email = 'lab@sante.com' THEN 'LAB_ATTENDANT'
    ELSE 'CUSTOMER'
END
WHERE role IS NULL OR role = '';

ALTER TABLE users ALTER COLUMN role SET NOT NULL;

CREATE TABLE IF NOT EXISTS email_verification_token (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    token VARCHAR(120) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE
);
